### OpenWeatherMap
- https://openweathermap.org/ <br><br>
- 기본적으로 유료이지만, 현재 날씨와 5일까지의 날시는 무료로 사용가능

In [1]:
import requests
import json

In [35]:
apiKey = '05d875bf91fb32599a6f8828a9f3f14f'

In [36]:
# 날씨를 확인할 도시 지정하기
cities = ['Seoul,KR','Tokyo,JP','New York,US','Beijing,CN']

In [37]:
api="http://openweathermap.org/data/2.5/weather?q={city}&APPID={key}"

In [38]:
# 켈빈 온도를 섭씨 온도로 변환
k2c = lambda k: k - 273.15

In [42]:
url = api.format(city=cities[0],key=apiKey)
r = requests.get(url)
print(r)
data = json.loads(r.text)
print(data)

<Response [401]>
{'cod': 401, 'message': 'Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.'}

---
### Naver API로 위도 경도 가져오기

In [44]:
import pandas as pd

In [72]:
foot=pd.read_csv('../Data/gajok.csv')
addresses=list(foot['Address'])

In [73]:
addresses

['서울시 서초구 서초대로73길 42(서초동)',
 '서울특별시 강남구 봉은사로57길 5(삼성동)',
 '서울시 용산구 한남대로 21길 32(한남동)',
 '서울시 강남구 일원로 9길 55(일원동)',
 '서울시 성동구 상원1길 42(성수동)',
 '서울시 강남구 수서동 716 사이룩스 109,110호',
 '서울시 광진구 구의1동 252-39',
 '서울시 송파구 가락동 97-8 104호',
 '서울시 성동구 용답동 58-6번지',
 '서울시 광진구 능동 222-10',
 '서울시 중구 광희동1가 143-2 뉴금호타워 1층',
 '서울시 종로구 종로 350(숭인동)',
 '서울시 광진구 광장동 320-15',
 '서울시 관악구 신림동길 5',
 '서울시 중구 중림동 1154 더플레이스 1층',
 '서울시 종로구 관철동 19-19',
 '서울시 종로구 낙원동 235-5',
 '서울시 동작구 대방동 400-5',
 '서울시 영등포구 신풍로122, 1층 (신길동)',
 '서울시 강동구 양재대로89가길 6(성내동)',
 '서울시 관악구 신림동 606-5 1층',
 '경기 성남시 수정구 위례서일로3길 4-6(창곡동)',
 '서울특별시 종로구 내자동 30',
 '서울시 강동구 길동 414-1',
 '경기도 성남시 수정구 위례순환로4길 26(위례동)',
 '서울시 동대문구 회기로 152 (회기동)',
 '서울시 영등포구 영중로4길 18 1층(영등포동)',
 '서울시 영등포구 영등포동 3가 9-23',
 '경기도 안양시 동안구 동편로20번길28 102호(관양동)',
 '경기도 안양시 동안구 인덕원로24번길 53, 1층(관양동)',
 '서울시 강동구 명일동 344-16',
 '경기도 성남시 중원구 광명로 86-4(성남동)',
 '서울시 금천구 독산4동 285-23',
 '경기도 성남시 분당구 삼평동 670 유스페이스 1B동 1층',
 '서울시 영등포구 당산동2가 164',
 '경기도 성남시 중원구 산성대로 4669(금광동)',
 '경기도 성남시 중원구 금광동 15',
 '경기도 성남시 분당구 야탑로 105번길 17 인제빌딩 (야탑동)',
 '경기도 성남시 중원구 하대원동 132-8',
 '서울시 성북구 정릉1동 227-33',
 '서울시 중랑구 망우동 357-15',
 '서울시 성북구 석관동 132-15',
 '서울시 서대문구 북가좌동 478 DMC래미안e편한세상 201동 13호',
 '경기도 남양주시 다산순환로 397-71(다산동)',
 '서울시 중랑구 공릉로32, B07호(묵동)',
 '경기도 안양시 동안구 평촌대로 117번길 23(호계동)',
 '경기도 안양시 만안구 안양동 674-94',
 '서울시 은평구 응암동 592-72',
 '서울시 중랑구 신내동 646번지 금강리빙스텔 136호',
 '서울시 마포구 상암동 2-88',
 '서울시 구로구 개봉동 179-24',
 '서울시 노원구 공릉동 392-2',
 '서울시 강서구 화곡동 779-2번지',
 '경기도 광명시 광명동 158-799',
 '경기도 성남시 분당구 정자동 63-1',
 '세종시 새롬중앙로34 크리스마스빌딩 1층',
 '경기도 하남시 미사강변북로 30번길 154(망월동)',
 '서울시 강북구 수유동 192-51',
 '서울시 은평구 불광로 111(불광동)',
 '경기도 하남시 신장로 107(신장동)',
 '서울시 강서구 등촌동 506-34',
 '서울시 노원구 동일로 203 가길 29 브라운스톤 140호(중계동)',
 '서울시 강서구 화곡동 898-16',
 '경기도 구리시 갈매중앙로 55번길 96-1(갈매동)',
 '서울시 은평구 갈현동 400-1',
 '경기도 성남시 분당구 금곡동 147번지 135호',
 '서울시 강서구 등촌동 63-12',
 '경기도 남양주시 다산중앙로82번안길 114(다산동)',
 '서울시 도봉구 창동 12-2',
 '서울시 노원구 중계동 359-20(태경빌딩 1층)',
 '경기도 부천시 소사구 옥길동 729-2',
 '서울시 강서구 마곡중앙6로 93 열린프라자 1층(마곡동)',
 '서울시 노원구 중계동 144-7',
 '서울시 노원구 노원로 34길 110(상계동)',
 '서울시 도봉구 마들로 663(방학동)',
 '서울시 노원구 상계동 1120-27',
 '경기도 의왕시 부곡중앙로17(삼동 192-24)',
 '경기도 남양주시 별내동 826-7 서울프라자 1층',
 '경기도 용인시 수지구 성복동 70-1 데이파크C동 126호, 127호 ',
 '경기도 광주시 오포읍 능평로 191(능평리)',
 '경기도 수원시 영통구 이의동 1317-1',
 '경기도 광주시 태전동 262-2',
 '경기도 시흥시 비둘기공원5길 15 은행프라자 (대야동)',
 '경기도 광주시 경안동 73-55',
 '경기도 수원시 장안구 정자동 876-1',
 '경기도 수원시 장안구 율전동 297-2번지 1층',
 '경기도 고양시 덕양구 신원동 625번지',
 '경기도 안산시 상록구 건건8길 3-4(건건동)',
 '경기도 용인시 기흥구 구성로 71(언남동)',
 '경기도 의정부시 호원동 454-24 아성빌딩 1층',
 '경기도 시흥시 능곡군자로50, 1층',
 '경기도 부천시 상동 535-9 시그마타워 1층',
 '경기도 용인시 기흥구 영덕동 987-5',
 '경기도 수원시 권선구 금곡동 1089 건우프라자 103호',
 '경기도 수원시 팔달구 인계동 1039-15',
 '경기도 의정부시 호원동 312-3 1층',
 '경기도  수원시 권선구 탑동 862-1',
 '경기도 안산시 단원구 고잔동 540-5',
 '경기도 김포시 고촌읍 장차로 29번지(신곡리 484-2)',
 '경기도 안산시 상록구 이동 715-9',
 '인천광역시 남동구 서창동 706',
 '경기도 안산시 단원구 선부광장로27, 114호(선부동)',
 '인천광역시 계양구 계양문화로 54 대산월드프라자 1층(계산동)',
 '경기도 용인시 기흥구 강남로8',
 '경기도 용인시 기흥구 중동 829 골드프라자 C동 118호, 119호',
 '인천광역시 남동구 하촌로71번길 9(만수동)',
 '경기도 안산시 상록구 샘골로 124(본오동)',
 '안산시 단원구 고잔동 622-17 1층 / 보화로 9',
 '경기도 의정부시 의정부2동 511',
 '경기도 남양주시 오남읍 진건오남로 778 선일프라자(오남리 761-27)',
 '경기도 의정부시 오목로 225번길 30(민락동)',
 '경기도 수원시 영통구 권선로908번길 22(신동)',
 '경기도 광주시 초월읍 쌍동리 199-1번지',
 '인천시 남동구 간석3동 921-14',
 '경기도 용인시 기흥구 한보라2로 11, 101호(보라동 579-3)',
 '경기도 안산시 단원구 초지동로 45(초지동)',
 '경기도 고양시 일산동구 위시티2로 11번길 45(식사동)',
 '경기도 안산시 단원구 신길동 1647번지',
 '경기도 수원시 권선구 곡반정동 557-12',
 '경기도 의정부시 금오동 473-4',
 '경기도 화성시 반월동 869 현대프라자 126호',
 '인천광역시 남동구 논현동 622-4',
 '경기도 남양주시 진접읍 해밀예당3로134 1층 진접플라자(금곡리)',
 '경기도 의정부시 녹양동 진등로 14(녹양동)',
 '경기 고양시 일산동구 무궁화로 43-15(장항동)',
 '경기도 김포시 풍무로 133번지(풍무동)',
 '경기도 용인시 처인구 포곡읍 포곡로 108번길 6(둔전리 151-8)',
 '경기도 남양주시 화도읍 마석로 112(마석우리)',
 '경기도 시흥시 중심상가로332 1층(정왕동)',
 '경기도 화성시 봉담읍 장등1길 3-17',
 '경기도 화성시 진안동 874-3',
 '경기도 시흥시 정왕동 1858-7',
 '경기도 화성시 봉담읍 와우리 38-1',
 '경기도 화성시 동탄대로 14길 5-42(오산동)',
 '경기도 화성시 동탄중심상가2길 26-31(반송동)',
 '경기도 용인시 처인구 김량장동 133-69',
 '경기도 화성시 지산2길 7(영천동)',
 '경기도 화성시 동탄산척로2나길 4-12',
 '인천시 서구 연희동 799-16 청라매그놀리아오피스텔 B01',
 '경기도 양주시 광사동 652-1 오션타워1층 ',
 '인천광역시 미추홀구 용현동 286-4 인하아티스타 1층',
 '경기도 김포시 김포한강 11로 310(운양동 리엔포레1차 상가)(운양동)',
 '경기도 오산시 금암동 500-2',
 '인천광역시 서구 검단로 459번길 3-1 1층(왕길동)',
 '경기도 화성시 왕배산2길 4-21(목동)',
 '경기도 김포시 김포한강1로78번길 31-7(장기동)',
 '경기도 파주시 와동동 1564-6',
 '경기도 양주시 옥정동 963-15 양주M타워(1층120,121호)',
 '경기도 화성시 경기동로 317번 가길 4-2(장지동)',
 '경기도 용인시 처인구 이동면 백옥대로 630 (천리)',
 '경기도 화성시 남양읍 남양리 2061-1',
 '경기도 파주시 금촌동 944-3번지 인오빌딩 1층',
 '경기도 양주시 고암동 159-1',
 '경기도 오산시 궐동 699-2',
 '경기도 오산시 원동 813-6',
 '경기도 김포시 김포한강9로75번길 190, 107호',
 '경기도 오산시 갈곶동 162-4',
 '경기도 화성시 향남읍 행정리 506-12',
 '경기도 이천시 송정동 82',
 '경기 화성시 향남읍 하길리 1465-4 에코프라자110호(향남읍)',
 '경기도 이천시 창전동 160-35',
 '경기도 동두천시 지행동 695-1',
 '경기도 이천시 갈산동 550번지',
 '경기 평택시 지산3로 65-5 (독곡동)',
 '경기도 파주시 문산읍 방촌로 1719-62',
 '지번경기 포천시 신읍동 46-28',
 '인천광역시 중구 신도시남로142번길 11-6(운서동)',
 '경기도 평택시 서정동 815-12',
 '경기도 이천시 부발읍 아미리 737-13',
 '경기도 평택시 고덕면 고덕여염 12길 82',
 '인천광역시 강화군 길상면 온수리 551-2',
 '경기도 평택시 동삭동 661-2 1층',
 '경기도 평택시 청북면 옥길리 1161-5',
 '경기도 평택시 비전동 1098-1 희성프라자 1층',
 '경기도 평택시 비전동 1070',
 '경기도 평택시 평택동 286-7',
 '경기도 평택시 용이동 464-2',
 '경기도 안성시 공도읍 공도2로 7(만정리)',
 '경기도 안성시 금산동 193-3',
 '경기도 평택시 안중로18번길 3',
 '경기도 여주시 세종로 85번지 (홍문동 274-6)',
 '경기도 평택시 포승읍 도곡리 1150-10',
 '경기도 안성시 아양2로 87(석정동)',
 '경기도 평택시 팽성읍 송화리 776-2',
 '충남 아산시 둔포면 둔포리 381번지',
 '충남 당진시 송악읍 복운리 1651-10',
 '충남 천안시 서북구 성환읍 매주리 317-2',
 '충남 당진시 송산면 서정4길 22(유곡리)',
 '충남 천안시 서북구 직산읍 삼은리 300',
 '충남 천안시 서북구 성거읍 성거길 123 대주프라자 1층(저리 66-2)',
 '충남 천안시 서북구 차암동 493번지',
 '충남 당진시 시곡동 반촌로 27-17',
 '충남 천안시 서북구 두정동 891',
 '천안시 서북구 1공단 1길52(두정동)',
 '충북 음성군 금왕읍 무극리 588-7',
 '충남 천안시 서북구 백석동 1160번지',
 '강원도 춘천시 동내면 거두리 926-4',
 '충남 당진시 읍내동 1493',
 '충남 천안시 서북구 성정동 855',
 '충남 천안시 동남구 터미널8길 17(신부동)',
 '강원도 원주시 지정면 신지정로 153-12 1층(가곡리)',
 '충남 천안시 불당동 705번지',
 '강원도 춘천시 후석로 278(후평동)',
 '충남 천안시 서북구 쌍용동 987번지 ',
 '세종시 보듬3로 8-29 해피라움 6차 104호(도담동 677)',
 '충남 아산시 신창면 남성리 213-1',
 '충남 천안시 동남구 청수동 216-102',
 '충남 아산시 배방읍 장재리 1530(용연로)',
 '충남 아산시 번영로 82(온천동)',
 '충남 천안시 동남구 신방동 71-8',
 '충북 음성군 맹동면 두성리 1260',
 '충남 아산시 모종동 717번지',
 '충남 천안시 동남구 청당동 597',
 '충남 아산시 용화동 1246',
 '충북 진천군 교성리 31-3',
 '충남 아산시 배방읍 배방로 35-2 D동 1,2호 (공수리151-51)',
 '충남 아산시 배방읍 월천2길 8-20 한영빌딩102호(복수리)',
 '강원도 원주시 단계동 841-1',
 '충청남도 천안시 동남구 목천읍 신계리 129 가동 1층',
 '강원도 원주시 혁신로 35',
 '충북 충주시 중앙탑면 원앙5길 8(용전리)',
 '충남 서산시 성연3로 111(오사리)',
 '충남 예산군 예산읍 산성리 708',
 '충북 증평군 증평읍 초중1길 30 (초중리 535-1)',
 '충청북도 청원군 오창읍 각리 651-5',
 '충남 서산시 동문동 194-3',
 '충남 서산지 예천동 1301-1번지',
 '충북 충주시 연수동 1477',
 '충남 홍성군 홍북면 신경리 580 에이원프라자 1층 106호',
 '충북 청주시 흥덕구 오송읍 만수리 525 거송빌딩 1층',
 '충정북도 청주시 송화로 166번길 7-3(송절동)',
 '충북 충주시 남산로 80(용산동)',
 '충북 청주시 청원구 주성동 348',
 '충북 청주시 흥덕구 복대동 292-17번지 1층 103호',
 '세종시 조치원읍 침산리 262-12',
 '충남 태안군 태안읍 동문1길, 50 민중빌딩1층(동문리 880-2)',
 '충북 청주시 흥덕구 강서로 108',
 '충북 청주시 상당구 북문로2가 59-6 (중앙로)',
 '충북 청주시 상당구 산성로 104번길 21(용담동)',
 '충남 홍성군 월산로50번길 15 103호(월산리)',
 '충북 청주시 서원구 산남동 588',
 '충북 청주시 상당구 중고개로125번길 15(용암동)',
 '충북 청주시 상당구 1순환로 1253번길 34(용암동)',
 '세종시 마음로 240(고운동)',
 '충북 제천시 청전동 497-72',
 '충북 제천시 장락동 552-9',
 '세종시 나성로 133-15 애플타워 1층(나성동)',
 '충남 공주시 신관동 655-9',
 '세종시 한누리대로 2149 엔젤타워 1층(보람동)',
 '전남 순천시 조례동 1698-1',
 '경남 김해시 장등로19번길 67-1(전영리)',
 '전라남도 순천시 해룡면 매안3길 27',
 '전남 광양시 오류3길 14(중동)',
 '울산시 울주군 범서읍 구영리 375-2',
 '울산광역시 북구 매곡로 97-1(매곡동)',
 '울산광역시 남구 대학로147번길 48(무거동)',
 '울산광역시 중구 유곡동 480-6',
 '울산시 북구 박상진4로 4 1층',
 '울산광역시 중구 태화강국가정원길 231-7(태화동)',
 '울산광역시 중구 약사동 625-25(곽남길 11)',
 '경남 양산시 물금읍 범어리 2688-15',
 '경남 양산시 중부동 691-3',
 '경남 사천시 벌리동 252-7',
 '울산광역시 남구 왕생로 27 1층(달동)',
 '경남 양산시 물금읍 새실로 159 나래메트로시티 D동 116호(가촌리 1280-4)',
 '울산광역시 남구 신선로 65번길 5(야음동)',
 '경남 양산시 동면 금오 14길 15-20 1층(석산리)',
 '경남 양산시 평산동 104-6번지 103호',
 '전남 무안군 삼향읍 남악리 2182 우솔빌딩 1층',
 '전남 목포시 연산백련로 25-1(연산동)',
 '경상남도 고성군 고성읍 동외로151번길 7',
 '전남 목포시 상동 1139번지 기흥빌딩',
 '전남 목포시 원산중앙로7 진프라자 110호(산정동)',
 '부산광역시 북구 금곡대로 285번길62, 103호(스카이타워)(화명동)',
 '부산시 기장군 정관면 매학리 714-11(정관읍)',
 '울산광역시 동구 해수욕장길 4',
 '전남 영암군 삼호읍 용앙리 315-37',
 '부산광역시 금정구 수림로 66번길 101(구서동)',
 '전라남도 여수시 예울마루로 37-26  114-1호',
 '전남 여수시 문수동 190-1',
 '부산시 사상구 모라동 1361번지 동원아파트 상가',
 '부산광역시 금정구 장전동 420-6',
 '부산시 동래구 온천동 1424-12 더리체 1층',
 '부산광역시 동래구 명장동 321-26',
 '전라남도 여수시 돌산읍 강남8길 34',
 '부산시 사상구 주례동 55-173',
 '부산광역시 연제구 연산동 1499-21',
 '부산광역시 동래구 안락동 468-54',
 '부산광역시 강서구 명지동 3254-10번지 ',
 '부산광역시 기장군 일광면 삼성리 840-4',
 '부산시 해운대구 반여동 1441-53',
 '부산광역시 사하구 하단동 527-4',
 '부산시 부산진구 부전동 232-14',
 '전남 강진군 강진읍 남성리 5-11',
 '부산광역시 수영구 광안동 50-6',
 '부산광역시 해운대구 세실로95',
 '경상남도 거제시 중곡로3길 22',
 '전남 해남군 해남읍 해리 361-2',
 '경남 거제시 아주동 1688-10',
 '경남 거제시 능포동 624-2',
 '제주특별자치도 제주시 화북일동 1023-4',
 '제주특별자치도 제주시 승천로72(아라이동)',
 '전북 전주시 덕진구 송천동2가 523-14',
 '충남 청양군 청양읍 칠갑산로8길 9(읍내리)',
 '대전광역시 대덕구 석봉동 316-12',
 '대전광역시 유성구 관들2길 72-11(관평동)',
 '대전시 유성구 봉명동 445-4 리베라 아이누리5차 1층',
 '대전광역시 대덕구 송촌동 465-8',
 '충남 보령시 동대동 476-23',
 '충청남도 계룡시 엄사면 엄사리 번영로88(엄사리)',
 '충남 부여군 부여읍 부장대로 49 (구아리 176-8)',
 '대전광역시 서구 관저동 1531번지 107호,108호',
 '충남 보령시 해수욕장8길 70 파레브호텔 1층(신흑동)',
 '충북 옥천군 옥천읍 중앙로10길 5',
 '경상북도 문경시 매봉로 64(모전동)',
 '충남 논산시 강산동 561번지',
 '경북 상주시 무양동 281-1번지',
 '강원도 속초시 미시령로 3389번길3(교동)',
 '강원도 속초시 청대로 40, KCC스위첸 상가 1층(조양동)',
 '강원도 고성군 토성면 토성로 131',
 '충남 서천군 서천읍 사곡로 50(사곡리)',
 '경북 영주시 휴천동 303-15',
 '충청북도 영동군 영동읍 계산리 687-22',
 '강원도 강릉시 선수촌로 79-15 (홍제동)',
 '경북 예천군 호명면 산합리 1428번지 1층',
 '전라북도 익산시 영등동 843-3',
 '전북 군산시 조촌동 2-21 세종빌딩 1층',
 '전북 완주군 봉동읍 둔산리 900-9',
 '전북 익산시 모현동1가  849',
 '전라북도 군산시 수송동 832-2',
 '전북 군산시 칠성로 168(소룡동)',
 '전북 군산시 나운동 481-10',
 '전북 군산시 미장10길 2(미장동)',
 '전북 익산시 동산동 1054-1',
 '경북 김천시 신음동 988-4',
 '전북 전주시 덕진구 편운로 26(여의동2가 573-7)',
 '전북 전주시 덕진구 송천동2가 1327-8 리빛타워 1층(세병2길)',
 '경북 안동시 옥동 787-15',
 '전북 전주시 덕진구 호성1길 6(우아동3가 594-32)',
 '전북 전주시 덕진구 권삼득로 343(덕진동)',
 '전북 전주시 덕진구 만성동 1372-2번지',
 '전북 전주시 완산구 서신동 고사평5길 3',
 '전라북도 전주시 덕진구 건산로 265',
 '경상북도 안동시 경동로 932(용상동)',
 '전라북도 전주시 덕진구 아중로 134-1(인후동)',
 '전라북도 전주시 완산구 전주객사3길 94, 1층',
 '전북 전주시 완산구 중동 779-7',
 '전북 전주시 완산구 효자동3가 1538-4',
 '전북 전주시 완산구 중화산동 2가 103-7',
 '전북 김제시 검산동 1059-7',
 '경북 구미시 봉곡동 441-3',
 '전북 전주시 완산구 효자동1가 669-9',
 '경상북도 구미시 고아읍 문성리 1282-1 1층',
 ' 전북 전주시 완산구 평화동 1가 730-2',
 '경북 구미시 형곡동 194-10',
 '경북 구미시 구미대로 382(신평동)',
 '경북 구미시 산동면 신당리 1421번지',
 '경북 구미시 옥계동 844-2',
 '경상북도 의성군 의성읍 문소3길 21',
 '경북 구미시 상모동 32-1',
 '경북 구미시 인의동 836-1',
 '전북 부안군 부안읍 봉덕리 835',
 '경북 칠곡군 석적읍 중리 200-7(북중리10길 2)',
 '경북 칠곡군 석적읍 남율리 1105번지',
 '경북 영양군 영양읍 서부리 150-11(시장길)',
 '전북 정읍시 수성동 937-2',
 '대구광역시 북구 연경중앙로3길23 103호 (연경동)',
 '경북 대구시 달성군 다사읍 매곡리 1547번지',
 '대구광역시 달서구 이곡동 1316-17',
 '대구광역시 북구 침산동 329-2 1층',
 '대구시 북구 복현2동 200-5',
 '대구시 달서구 달구벌대로 1706(두류동)',
 '대구광역시 달서구 장기동 820-11',
 '대구시 중구 종로2가 24번지',
 '대구광역시 달서구 조암로32, 111호(월성동)',
 '대구광역시 달성군 화원읍 명곡리 269-2',
 '전남 고창읍 교촌리 403(월곡로69)',
 '대구광역시 동구 동부로22길 43(신천동 323-3)',
 '대구시 남구 대명9동 813-2',
 '대구시 수성구 수성동4가 1023-2',
 '대구시 수성구 무학로 23길 59, 1층(두산동)',
 '전북 남원시 큰들2길 11-1(도통동)',
 '대구광역시 동구 신서동 1188',
 '대구광역시 달성군 유가면 테크노상업로 4길 12, 102호(봉리)',
 '경상북도 경산시 옥산동 741-12',
 '경북 영천시 망정1길 200(망정동)',
 '경북 경주시 안강읍 안강중앙로 154(산대리 )',
 '경북 포항시 북구 흥해읍 남성리 327-3',
 '경북 포항시 북구 양덕동 1413번지',
 '광주광역시 서구 금호동 757-8',
 '경북 포항시 남구 효자동 569-8번지',
 '경북 포항시 남구 상도동 632-10',
 '경북 경주시 동천동 769-3',
 '경북 포항시 남구 오천읍 원리 1081-4',
 '경남 진주시 평안동 132번지',
 '경남 진주시 하대동 304-29',
 '경상남도 진주시 평거동 781-5',
 '경상남도 진주시 범골로37번길 33-1',
 '경상남도 진주시 가호로 48',
 '전남 무안읍 무안읍 불무로 42(교촌리)',
 '경남 사천시 사천읍 평화리 46-6번지',
 '경북 경주시 외동읍 입실로 107(입실리)',
 '전남 순천시 오천6길 16, 정원타워 1층(오천동)']

In [77]:
url = 'https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query={addr}'
header = {'X-NCP-APIGW-API-KEY-ID': '2hossypbwr','X-NCP-APIGW-API-KEY': '7claUZjZEE9LdX6NcmFcROjdNXAqQUqafb1wBrE4'}

##### 경도 위도 붙이기

In [83]:
import time
import urllib.request
import json

In [112]:
lat = []
lng = []
wrong = []
index = 0
index_list = []
for address in addresses:
    try:
        encText =urllib.parse.quote(address)
        url = 'https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query='+ encText
        request = urllib.request.Request(url)
        request.add_header("X-NCP-APIGW-API-KEY-ID",'2hossypbwr')
        request.add_header("X-NCP-APIGW-API-KEY",'7claUZjZEE9LdX6NcmFcROjdNXAqQUqafb1wBrE4')
        response = urllib.request.urlopen(request)
        rescode = response.getcode()
        if(rescode==200):
            response_body = response.read()
            entext = response_body.decode('utf-8')
        else:
            print("Error Code:" + rescode)
        
        data = json.loads(entext)
        lat.append(data['addresses'][0]['y'])
        lng.append(data['addresses'][0]['x'])
        index += 1
    except Exception as e:
        print(e)
        print(address)
        wrong.append(address)
        index_list.append(index)
        lat.append('')
        lng.append('')
        index += 1

print(lat , lng , wrong, index_list)
print(len(lat),len(lng))

list index out of range
경기도 성남시 중원구 산성대로 4669(금광동)
list index out of range
경기도 광주시 오포읍 능평로 191(능평리)
list index out of range
경기도 의정부시 녹양동 진등로 14(녹양동)
list index out of range
경기도 화성시 경기동로 317번 가길 4-2(장지동)
list index out of range
지번경기 포천시 신읍동 46-28
list index out of range
경기도 평택시 고덕면 고덕여염 12길 82
list index out of range
충남 당진시 시곡동 반촌로 27-17
list index out of range
충남 서산지 예천동 1301-1번지
list index out of range
충정북도 청주시 송화로 166번길 7-3(송절동)
list index out of range
충청남도 계룡시 엄사면 엄사리 번영로88(엄사리)
list index out of range
전북 전주시 완산구 서신동 고사평5길 3
list index out of range
전남 고창읍 교촌리 403(월곡로69)
list index out of range
전남 무안읍 무안읍 불무로 42(교촌리)
['37.5012293', '37.5112143', '37.5334689', '37.4907614', '37.5470048', '37.4884576', '37.5376393', '37.4948578', '37.5643802', '37.5560865', '37.5656293', '37.5729857', '37.5471523', '37.4873443', '37.5589817', '37.5692890', '37.5723404', '37.4997029', '37.4997374', '37.5263098', '37.4748960', '37.4652056', '37.5764165', '37.5372297', '37.4696623', '37.5910749', '37.5173915', '37.5172941', '37.4053892', '37.3999937', '37.5466801', '37.4344706', '37.4695213', '37.4006981', '37.5235106', '', '37.4446418', '37.4112991', '37.4300295', '37.6104506', '37.6008024', '37.6129057', '37.5745339', '37.6214386', '37.6139716', '37.3821772', '37.3998608', '37.5886572', '37.6163279', '37.5779565', '37.4960275', '37.6265285', '37.5321489', '37.4784878', '37.3692396', '36.4845919', '37.5706093', '37.6388395', '37.6166939', '37.5373018', '37.5506028', '37.6399301', '37.5298021', '37.6309928', '37.6199459', '37.3510016', '37.5627795', '37.6123651', '37.6531845', '37.6519970', '37.4689753', '37.5601357', '37.6600440', '37.6638045', '37.6693045', '37.6756289', '37.3211280', '37.6663745', '37.3130683', '', '37.2947713', '37.3921448', '37.4426557', '37.4122942', '37.2964160', '37.2981366', '37.6638550', '37.3116983', '37.2950034', '37.7100686', '37.3693583', '37.5063508', '37.2743834', '37.2728006', '37.2658871', '37.7239159', '37.2686451', '37.3179448', '37.6046505', '37.3092261', '37.4228870', '37.3362214', '37.5355074', '37.2709161', '37.2776861', '37.4542956', '37.2947952', '37.3320534', '37.7373701', '37.6971373', '37.7467355', '37.2479130', '37.3725330', '37.4611340', '37.2544399', '37.3077973', '37.6790045', '37.3319533', '37.2393411', '37.7513232', '37.2350476', '37.4023482', '37.7212437', '', '37.6637955', '37.6075377', '37.2687358', '37.6603355', '37.3364791', '37.2229154', '37.2139935', '37.3538916', '37.2141932', '37.1847093', '37.2069678', '37.2365074', '37.2060224', '37.1746580', '37.5326269', '37.7949043', '37.4475243', '37.6553279', '37.1755973', '37.6016556', '37.1801634', '37.6442712', '37.7352277', '37.8185485', '', '37.1929104', '37.2026619', '37.7581873', '37.8307219', '37.1563914', '37.1465956', '37.6450384', '37.1312271', '37.1252757', '37.2905421', '37.1161632', '37.2801808', '37.8926727', '37.2879022', '37.0807466', '37.8672708', '', '37.4944324', '37.0677114', '37.2539354', '', '37.6408059', '37.0099549', '37.0176425', '37.0013791', '37.0029793', '36.9930749', '36.9951871', '37.0000970', '37.0123655', '36.9833521', '37.2903340', '36.9870103', '37.0102122', '36.9638706', '36.9256954', '36.9425458', '36.9129300', '36.9593810', '36.8780934', '36.8762818', '36.8395326', '', '36.8324160', '36.8323895', '36.9904977', '36.8269347', '37.8552632', '36.9016127', '36.8206990', '36.8220153', '37.3738543', '36.8113017', '37.8764293', '36.8046027', '36.5151121', '36.7936828', '36.7962895', '36.7886555', '36.7864469', '36.7888107', '36.9098602', '36.7781466', '36.7842619', '36.7747135', '36.8541277', '36.7737853', '36.7721778', '37.3477193', '36.7723217', '37.3242961', '37.0185681', '36.8283687', '36.6932820', '36.7764801', '36.7081817', '36.7794002', '', '36.9833697', '36.6598123', '36.6303366', '', '36.9615147', '36.6707261', '36.6397797', '36.6035085', '36.7493329', '36.6243888', '36.6374819', '36.6316741', '36.5996114', '36.6117782', '36.6156119', '36.6090183', '36.5181619', '37.1437661', '37.1596338', '36.4905180', '36.4726086', '36.4778100', '34.9558122', '35.3086237', '34.9291266', '34.9372275', '35.5697380', '35.6413899', '35.5516535', '35.5594479', '35.5996222', '35.5516153', '35.5684658', '35.3296127', '35.3366077', '34.9392020', '35.5359498', '35.3152964', '35.5221205', '35.3171128', '35.3806821', '34.8123394', '34.8175897', '34.9747772', '34.7984351', '34.8071031', '35.2344542', '35.3225003', '35.4966335', '34.7464953', '35.2442059', '34.7469786', '34.7503563', '35.1845688', '35.2303449', '35.2059365', '35.2087927', '34.7203310', '35.1497598', '35.1837882', '35.1994279', '35.0866085', '35.2645792', '35.1989861', '35.1074178', '35.1529135', '34.6378671', '35.1675796', '35.1729677', '34.8939394', '34.5699361', '34.8665622', '34.8773676', '33.5144570', '33.4923034', '35.8667898', '36.4499343', '36.4449362', '36.4243534', '36.3550990', '36.3645181', '36.3451783', '', '36.2796723', '36.2971522', '36.3121552', '36.3022184', '36.5902004', '36.1946558', '36.4181548', '38.2070313', '38.1847928', '38.2567968', '36.0834548', '36.8122027', '36.1744642', '37.7578147', '36.5757712', '35.9602096', '35.9766005', '35.9596936', '35.9515037', '35.9661253', '35.9698434', '35.9664620', '35.9619421', '35.9339244', '36.1359786', '35.8716583', '35.8733194', '36.5632328', '35.8560424', '35.8454014', '35.8433659', '', '35.8355942', '36.5556224', '35.8252410', '35.8213564', '35.8348440', '35.8167403', '35.8117659', '35.8020516', '36.1430859', '35.7988260', '36.1611938', '35.7944913', '36.1075661', '36.1207751', '36.1553158', '36.1370065', '36.3479898', '36.0883215', '36.1049780', '35.7231328', '36.0767551', '36.0680641', '36.6620926', '35.5803041', '35.9431032', '35.8599814', '35.8603747', '35.8911821', '35.8971511', '35.8555137', '35.8420424', '35.8690843', '35.8251875', '35.7994246', '', '35.8728109', '35.8384150', '35.8615129', '35.8328500', '35.4152689', '35.8772071', '35.6928166', '35.8269134', '35.9824973', '35.9931141', '36.1062112', '36.0800986', '35.1330303', '36.0060289', '36.0137190', '35.8570496', '35.9707473', '35.1973967', '35.1937870', '35.1715924', '35.1699117', '35.1636013', '', '35.0836616', '35.7178772', '34.9339247'] ['127.0244570', '127.0451360', '127.0063017', '127.0859860', '127.0471344', '127.1041957', '127.0840358', '127.1184284', '127.0533574', '127.0804468', '127.0063878', '127.0164185', '127.1080094', '126.9281800', '126.9660587', '126.9847754', '126.9885839', '126.9208381', '126.9197477', '127.1347396', '126.9182265', '127.1388352', '126.9706053', '127.1377495', '127.1497905', '127.0531198', '126.9084220', '126.9068091', '126.9724973', '126.9754819', '127.1447122', '127.1384105', '126.8990560', '127.1070254', '126.8948961', '', '127.1591913', '127.1302316', '127.1504946', '127.0151151', '127.1010217', '127.0653210', '126.9118155', '127.1588834', '127.0781762', '126.9590830', '126.9233526', '126.9143990', '127.0926931', '126.8959699', '126.8589101', '127.0756355', '126.8628990', '126.8534120', '127.1133309', '127.2524926', '127.1826895', '127.0245121', '126.9325423', '127.2061140', '126.8637789', '127.0642714', '126.8475496', '127.1160257', '126.9193394', '127.1104318', '126.8509702', '127.1646532', '127.0503050', '127.0770309', '126.8217934', '126.8376979', '127.0756638', '127.0663365', '127.0459932', '127.0568543', '126.9508496', '127.1176085', '127.0790027', '', '127.0557104', '127.2309178', '126.7904931', '127.2568920', '126.9939749', '126.9692206', '126.8891915', '126.9053897', '127.1173933', '127.0476379', '126.8062714', '126.7553224', '127.0704193', '126.9422271', '127.0320975', '127.0458141', '126.9752135', '126.8395537', '126.7709275', '126.8510382', '126.7498219', '126.8104466', '126.7368598', '127.1272601', '127.1535923', '126.7332873', '126.8632470', '126.8284980', '127.0400234', '127.2050007', '127.0982241', '127.0449923', '127.3011096', '126.7207851', '127.1109700', '126.8166373', '126.8122084', '126.7871966', '127.0298047', '127.0695999', '127.0619411', '126.7219820', '127.1954434', '', '126.7679569', '126.7226282', '127.2179188', '127.3036677', '126.7486776', '126.9449137', '127.0406272', '126.7229600', '126.9766692', '127.1037868', '127.0736369', '127.2055566', '127.1132638', '127.1143391', '126.6507650', '127.0781276', '126.6515632', '126.6831804', '127.0505680', '126.6549064', '127.1247942', '126.6714863', '126.7566994', '127.0927990', '', '127.2072383', '126.8271532', '126.7714135', '127.0683746', '127.0556611', '127.0751286', '126.6250440', '127.0687563', '126.9236243', '127.4445940', '126.9115397', '127.4443728', '127.0540215', '127.4621459', '127.0637484', '126.7837441', '', '126.4922266', '127.0630357', '127.4896412', '', '126.4919188', '127.0925938', '126.9165953', '127.1144271', '127.1056799', '127.0909358', '127.1384032', '127.1691712', '127.2661720', '126.9254303', '127.6355847', '126.8464805', '127.2567746', '127.0580077', '127.0375363', '126.7831562', '127.1301564', '126.6916624', '127.1512081', '127.2026254', '127.1022876', '', '127.1343667', '127.1479778', '127.5829727', '127.1226215', '127.7513180', '126.6296167', '127.1357363', '127.1590179', '127.8790316', '127.1102028', '127.7527420', '127.1298834', '127.2578202', '126.9533728', '127.1526577', '127.0892093', '126.9999441', '127.1270125', '127.5439981', '127.0234238', '127.1584462', '127.0102114', '127.4454674', '127.0552478', '127.0756620', '127.9324286', '127.2086890', '127.9781362', '127.8267181', '126.4471499', '126.8304907', '127.5673757', '127.4163294', '126.4648784', '', '127.9393244', '126.6810323', '127.3307060', '', '127.9410941', '127.4963055', '127.4317684', '127.2916972', '126.3037939', '127.4285760', '127.4890960', '127.5058031', '126.6472566', '127.4669568', '127.5173785', '127.5043514', '127.2325901', '128.2045629', '128.2249540', '127.2576567', '127.1364727', '127.2878469', '127.5186107', '128.7275627', '127.5513682', '127.6969658', '129.2452360', '129.3544850', '129.2600624', '129.2963790', '129.3619819', '129.2999334', '129.3424071', '129.0115290', '129.0280986', '128.0855039', '129.3318357', '129.0043873', '129.3194752', '129.0273588', '129.1515945', '126.4624233', '126.3906943', '128.3255214', '126.4326545', '126.3738902', '129.0100891', '129.1772651', '129.4280079', '126.4664016', '129.0870066', '127.6700279', '127.7001835', '128.9896397', '129.0855173', '129.0698141', '129.1026409', '127.7496094', '129.0132827', '129.0750579', '129.1109519', '128.9109841', '129.2264056', '129.1189535', '128.9659992', '129.0585712', '126.7691869', '129.1166116', '129.1756390', '128.6281697', '126.6069062', '128.6886626', '128.7319244', '126.5757279', '126.5424650', '127.1222885', '126.8038622', '127.4246885', '127.3918071', '127.3406563', '127.4391921', '126.6080158', '', '126.9086346', '127.3378018', '126.5132146', '127.5703737', '128.1809185', '127.0881819', '128.1524635', '128.5766370', '128.5957887', '128.5596645', '126.6883772', '128.6237141', '127.7771925', '128.8687300', '128.4927981', '126.9783261', '126.7405603', '127.1260845', '126.9400010', '126.7167721', '126.6793137', '126.7003545', '126.7311684', '126.9629550', '128.1169461', '127.0791218', '127.1273515', '128.7015977', '127.1558094', '127.1251502', '127.0773822', '', '127.1660856', '128.7564722', '127.1645430', '127.1414332', '127.0600063', '127.1108633', '127.1281484', '126.9026394', '128.3101642', '127.1154599', '128.3473219', '127.1333924', '128.3389394', '128.3630656', '128.4307747', '128.4186459', '128.6957678', '128.3549426', '128.4210786', '126.7399511', '128.4132823', '128.4040623', '129.1151233', '126.8566642', '128.6158826', '128.4643515', '128.5052194', '128.5907057', '128.6161141', '128.5523342', '128.5297246', '128.5914879', '128.5261983', '128.4944449', '', '128.6271014', '128.5767480', '128.6175214', '128.6216802', '127.3965581', '128.7321537', '128.4604993', '128.7273322', '128.9515744', '129.2169281', '129.3465439', '129.3973550', '126.8575892', '129.3352606', '129.3581784', '129.2239875', '129.4018701', '128.0839010', '128.1216394', '128.0649165', '128.1301747', '128.1115707', '', '128.0868861', '129.3232622', '127.4944088'] ['경기도 성남시 중원구 산성대로 4669(금광동)', '경기도 광주시 오포읍 능평로 191(능평리)', '경기도 의정부시 녹양동 진등로 14(녹양동)', '경기도 화성시 경기동로 317번 가길 4-2(장지동)', '지번경기 포천시 신읍동 46-28', '경기도 평택시 고덕면 고덕여염 12길 82', '충남 당진시 시곡동 반촌로 27-17', '충남 서산지 예천동 1301-1번지', '충정북도 청주시 송화로 166번길 7-3(송절동)', '충청남도 계룡시 엄사면 엄사리 번영로88(엄사리)', '전북 전주시 완산구 서신동 고사평5길 3', '전남 고창읍 교촌리 403(월곡로69)', '전남 무안읍 무안읍 불무로 42(교촌리)'] [35, 79, 123, 148, 165, 169, 191, 226, 230, 309, 341, 376, 399]
403 403

In [113]:
foot=pd.read_csv('../Data/gajok.csv')
# dataframe에 컬럼 추가
foot['lat'] = lat
foot['lng'] = lng
foot

,Name,Address,Phone,Image,lat,lng
0,강남1호점,서울시 서초구 서초대로73길 42(서초동),02-595-5849,https://gajok.kr/upload/store/none01.png,37.5012293,127.0244570
1,선정릉점,서울특별시 강남구 봉은사로57길 5(삼성동),02-543-5849,https://gajok.kr/upload/store/none01.png,37.5112143,127.0451360
2,한남오거리점,서울시 용산구 한남대로 21길 32(한남동),02-797-1231,https://gajok.kr/upload/store/gksskadhrjfl01.png,37.5334689,127.0063017
3,일원점,서울시 강남구 일원로 9길 55(일원동),02-3412-0070,https://gajok.kr/upload/store/dlfdnjs01.png,37.4907614,127.0859860
4,뚝섬역점,서울시 성동구 상원1길 42(성수동),02-468-7535,https://gajok.kr/upload/store/none01.png,37.5470048,127.0471344
...,...,...,...,...,...,...
398,진주호탄점,경상남도 진주시 가호로 48,055-761-7989,https://gajok.kr/upload/store/20221206123356_7...,35.1636013,128.1115707
399,전남무안점,전남 무안읍 무안읍 불무로 42(교촌리),061-454-5849,https://gajok.kr/upload/store/none01.png,,
400,경남사천점,경남 사천시 사천읍 평화리 46-6번지,055-854-5445,https://gajok.kr/upload/store/rudskatkcjs01.png,35.0836616,128.0868861
401,경주외동점,경북 경주시 외동읍 입실로 107(입실리),054-777-4123,https://gajok.kr/upload/store/rudwndhlehd01.png,35.7178772,129.3232622
402,순천오천점,"전남 순천시 오천6길 16, 정원타워 1층(오천동)",061-741-5849,https://gajok.kr/upload/store/none01.png,34.9339247,127.4944088

In [114]:
# csv로 저장
foot.to_csv('../Data/gajok+lat+lng.csv',encoding='utf-8',index=False)